### ISSUE TITLE
Save items!

### ISSUE THREAD

**Issue by joicenunes** [matchu/impress-2020#3]
One thing that I love in old dress to impress is the possibility of "save" all items that I liked to choose between them when I finish one search. If possible please bring it back to the new version?

**Comment by matchu** [comment]
Ah yes, this is live now! Log in and there will be a Save button by the outfit name 😊

![image](https://user-images.githubusercontent.com/59218/119913557-0ab74980-bf13-11eb-9ce8-4a71ac8cf798.png)

thank you!!
